# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 hamsci-mon contributors
version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git submodule update --init --recursive
sphinx:
  configuration: docs/conf.py
formats:
  - htmlzip
python:
  install:
    - requirements: docs/requirements.txt
